[package]
name = "jwk_example"
version = "0.1.0"
authors = ["lma <maylukas@gmail.com>"]
edition = "2018"

[dependencies]
jsonwebtoken = "7.1.1"
serde = "1.0.111"
lazy_static = "1.4.0"
log = "0.4.8"
chrono = "0.4.11"
rocket = "0.4.5"
reqwest = { version = "0.10.6", features = ["blocking", "json"] }
